//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace RppitoNet.recolector_ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="recolectorSoap", Namespace="http://tempuri.org/")]
    public partial class recolector : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListadoRecolectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroVideoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public recolector() {
            this.Url = global::RppitoNet.Properties.Settings.Default.RppitoNet_recolector_ws_recolector;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListadoRecolectorCompletedEventHandler ListadoRecolectorCompleted;
        
        /// <remarks/>
        public event RegistroVideoCompletedEventHandler RegistroVideoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoRecolector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RecolectorBE[] ListadoRecolector(string pFecha, int pId_recolector) {
            object[] results = this.Invoke("ListadoRecolector", new object[] {
                        pFecha,
                        pId_recolector});
            return ((RecolectorBE[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoRecolectorAsync(string pFecha, int pId_recolector) {
            this.ListadoRecolectorAsync(pFecha, pId_recolector, null);
        }
        
        /// <remarks/>
        public void ListadoRecolectorAsync(string pFecha, int pId_recolector, object userState) {
            if ((this.ListadoRecolectorOperationCompleted == null)) {
                this.ListadoRecolectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoRecolectorOperationCompleted);
            }
            this.InvokeAsync("ListadoRecolector", new object[] {
                        pFecha,
                        pId_recolector}, this.ListadoRecolectorOperationCompleted, userState);
        }
        
        private void OnListadoRecolectorOperationCompleted(object arg) {
            if ((this.ListadoRecolectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoRecolectorCompleted(this, new ListadoRecolectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistroVideo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VideoBE RegistroVideo(int IdVideo) {
            object[] results = this.Invoke("RegistroVideo", new object[] {
                        IdVideo});
            return ((VideoBE)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroVideoAsync(int IdVideo) {
            this.RegistroVideoAsync(IdVideo, null);
        }
        
        /// <remarks/>
        public void RegistroVideoAsync(int IdVideo, object userState) {
            if ((this.RegistroVideoOperationCompleted == null)) {
                this.RegistroVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroVideoOperationCompleted);
            }
            this.InvokeAsync("RegistroVideo", new object[] {
                        IdVideo}, this.RegistroVideoOperationCompleted, userState);
        }
        
        private void OnRegistroVideoOperationCompleted(object arg) {
            if ((this.RegistroVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroVideoCompleted(this, new RegistroVideoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecolectorBE {
        
        private int idRecolectorField;
        
        private string tituloField;
        
        private string contenidoField;
        
        private string tipoVistaField;
        
        private int idseccionField;
        
        private int idTipoNoticiaField;
        
        private System.DateTime fechaField;
        
        private int idreporteroField;
        
        private string nomreporteroField;
        
        private int idvideoField;
        
        private int idimagenField;
        
        private int prioridadField;
        
        /// <remarks/>
        public int IdRecolector {
            get {
                return this.idRecolectorField;
            }
            set {
                this.idRecolectorField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoVista {
            get {
                return this.tipoVistaField;
            }
            set {
                this.tipoVistaField = value;
            }
        }
        
        /// <remarks/>
        public int Idseccion {
            get {
                return this.idseccionField;
            }
            set {
                this.idseccionField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoNoticia {
            get {
                return this.idTipoNoticiaField;
            }
            set {
                this.idTipoNoticiaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public int Idreportero {
            get {
                return this.idreporteroField;
            }
            set {
                this.idreporteroField = value;
            }
        }
        
        /// <remarks/>
        public string Nomreportero {
            get {
                return this.nomreporteroField;
            }
            set {
                this.nomreporteroField = value;
            }
        }
        
        /// <remarks/>
        public int Idvideo {
            get {
                return this.idvideoField;
            }
            set {
                this.idvideoField = value;
            }
        }
        
        /// <remarks/>
        public int Idimagen {
            get {
                return this.idimagenField;
            }
            set {
                this.idimagenField = value;
            }
        }
        
        /// <remarks/>
        public int prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VideoBE {
        
        private int idVideoField;
        
        private string linkField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int idVideo {
            get {
                return this.idVideoField;
            }
            set {
                this.idVideoField = value;
            }
        }
        
        /// <remarks/>
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListadoRecolectorCompletedEventHandler(object sender, ListadoRecolectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoRecolectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoRecolectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RecolectorBE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RecolectorBE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegistroVideoCompletedEventHandler(object sender, RegistroVideoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroVideoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroVideoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VideoBE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VideoBE)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591