<?xml version="1.0" encoding="utf-8"?><Database Name="RppDb" Class="RppDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=RppDb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RppDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Noticias" Member="Noticias">
    <Type Name="Noticia">
      <Column Name="IdNoticia" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Titulo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Seccion" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>